// Generated by game/scripts/generate-shared-swift-config.mjs.
// Do not edit by hand.

import Foundation
import CoreGraphics

enum SharedTrackerConfig {
    enum LaneBoundaries {
        static let leftMax: CGFloat = 0.3
        static let deadZoneLeft: CGFloat = 0.33
        static let deadZoneRight: CGFloat = 0.67
        static let rightMin: CGFloat = 0.7
    }

    enum DekeThresholds {
        static let enter: CGFloat = 0.25
        static let exit: CGFloat = 0.35
    }

    enum WebSocket {
        static let port = 5173
        static let trackerPath = "/ws/tracker"
        static let gamePath = "/ws/game"
    }

    enum MessageTypes {
        static let input = "input"
        static let state = "state"
    }
}
